"""APRS (Automatic Packet Reporting System) decoding and encoding.

>>> import packet_aprs
>>> packet = packet_aprs.decode("M0LTE-9>APZ001,WIDE1-1:!5130.00N/00007.00W>088/036Mobile")
>>> packet.data.latitude, packet.data.course_degrees, packet.data.comment
(51.5, 88, 'Mobile')
"""

from __future__ import annotations

from ._decode import decode_ax25, decode_kiss, decode_tnc2
from .diagnostics import Diagnostic, DiagnosticCode, Severity
from .errors import AprsError, EncodeError, HeaderError
from .model import (
    Ack,
    AgreloDf,
    AprsData,
    AreaColor,
    AreaObject,
    AreaShape,
    Beam,
    Bulletin,
    Capabilities,
    CommentTelemetry,
    CompressionOrigin,
    CompressionType,
    Dao,
    DaoPrecision,
    DfBearing,
    Dfs,
    DirectedQuery,
    Fix,
    Footprint,
    ItemReport,
    MaidenheadBeacon,
    Message,
    MicEMessage,
    MicEReport,
    NmeaFix,
    NmeaSentence,
    NmeaSource,
    NwsBulletin,
    ObjectReport,
    Phg,
    PositionedData,
    PositionlessWeather,
    PositionReport,
    Query,
    RawWeather,
    RawWeatherFormat,
    Reject,
    StatusReport,
    Storm,
    StormType,
    TelemetryBits,
    TelemetryCoefficients,
    TelemetryNames,
    TelemetryReport,
    TelemetryUnits,
    TestData,
    ThirdParty,
    Timestamp,
    TimestampKind,
    ToneType,
    Unrecognized,
    UnrecognizedReason,
    UserDefined,
    VoiceFrequency,
    Weather,
    WeatherExtra,
)
from .options import ParseOptions
from .packet import Packet, PathEntry, QConstruct
from .symbols import Symbol

__version__ = "0.1.0"

decode = decode_tnc2
"""Decode a TNC2 / APRS-IS line (``str`` or ``bytes``); see :func:`decode_tnc2`."""

__all__ = [
    "Ack",
    "AgreloDf",
    "AprsData",
    "AprsError",
    "AreaColor",
    "AreaObject",
    "AreaShape",
    "Beam",
    "Bulletin",
    "Capabilities",
    "CommentTelemetry",
    "CompressionOrigin",
    "CompressionType",
    "Dao",
    "DaoPrecision",
    "DfBearing",
    "Dfs",
    "Diagnostic",
    "DiagnosticCode",
    "DirectedQuery",
    "EncodeError",
    "Fix",
    "Footprint",
    "HeaderError",
    "ItemReport",
    "MaidenheadBeacon",
    "Message",
    "MicEMessage",
    "MicEReport",
    "NmeaFix",
    "NmeaSentence",
    "NmeaSource",
    "NwsBulletin",
    "ObjectReport",
    "Packet",
    "ParseOptions",
    "PathEntry",
    "Phg",
    "PositionReport",
    "PositionedData",
    "PositionlessWeather",
    "QConstruct",
    "Query",
    "RawWeather",
    "RawWeatherFormat",
    "Reject",
    "Severity",
    "StatusReport",
    "Storm",
    "StormType",
    "Symbol",
    "TelemetryBits",
    "TelemetryCoefficients",
    "TelemetryNames",
    "TelemetryReport",
    "TelemetryUnits",
    "TestData",
    "ThirdParty",
    "Timestamp",
    "TimestampKind",
    "ToneType",
    "Unrecognized",
    "UnrecognizedReason",
    "UserDefined",
    "VoiceFrequency",
    "Weather",
    "WeatherExtra",
    "__version__",
    "decode",
    "decode_ax25",
    "decode_kiss",
    "decode_tnc2",
]
