#!/usr/bin/env python3
"""Generate src/packet_aprs/_deviceid_data.py from the aprs-deviceid database.

  python3 tools/generate_devices.py path/to/aprs-deviceid/tocalls.yaml

The database (https://github.com/aprsorg/aprs-deviceid) is by Heikki Hannikainen, OH7LZB, under
CC BY-SA 2.0; see THIRD-PARTY-NOTICES.md. Contact addresses are left out. Needs PyYAML, which is
a development dependency only.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parent.parent / "src" / "packet_aprs" / "_deviceid_data.py"
KEEP = ("vendor", "model", "class", "os", "features")


def entry(item: dict[str, object]) -> tuple[object, ...]:
    features = item.get("features") or ()
    return (
        str(item.get("vendor", "")),
        str(item.get("model", "")),
        str(item.get("class", "")),
        str(item.get("os", "")),
        tuple(str(f) for f in features),  # type: ignore[union-attr]
    )


def main() -> int:
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "tocalls.yaml")
    db = yaml.safe_load(source.read_text(encoding="utf-8"))
    try:
        commit = subprocess.run(
            ["git", "-C", str(source.parent), "log", "-1", "--format=%h %cs"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        commit = "unknown"
    lines = [
        '"""The aprs-deviceid database, generated by tools/generate_devices.py. Do not edit.',
        "",
        "Source: https://github.com/aprsorg/aprs-deviceid (tocalls.yaml), commit " + commit + ",",
        "by Heikki Hannikainen, OH7LZB, licensed under CC BY-SA 2.0",
        "(https://creativecommons.org/licenses/by-sa/2.0/). Contact addresses are left out.",
        "Vendor and model names are copied verbatim.",
        '"""',
        "",
        "# fmt: off",
        "# ruff: noqa: E501, RUF001",
        "",
        "Entry = tuple[str, str, str, str, tuple[str, ...]]",
        '"""vendor, model, class, os, features"""',
        "",
        f"VERSION = {commit!r}",
        "",
        "CLASSES: dict[str, str] = {",
    ]
    for c in db.get("classes", []):
        lines.append(f"    {c['class']!r}: {c['shown']!r},")
    lines.append("}")
    lines.append("")
    lines.append("MICE: dict[str, Entry] = {")
    for item in db.get("mice", []):
        lines.append(f"    {item['suffix']!r}: {entry(item)!r},")
    lines.append("}")
    lines.append("")
    lines.append("MICE_LEGACY: dict[tuple[str, str], Entry] = {")
    for item in db.get("micelegacy", []):
        key = (item["prefix"], item.get("suffix", ""))
        lines.append(f"    {key!r}: {entry(item)!r},")
    lines.append("}")
    lines.append("")
    lines.append("TOCALLS: dict[str, Entry] = {")
    for item in db.get("tocalls", []):
        lines.append(f"    {str(item['tocall'])!r}: {entry(item)!r},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT}: {len(db.get('mice', []))} mice, {len(db.get('micelegacy', []))} legacy, {len(db.get('tocalls', []))} tocalls"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
